# Generated by Django 5.1.3 on 2024-12-23 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.RemoveField(
            model_name='film',
            name='people',
        ),
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.CreateModel(
            name='FilmCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024, verbose_name='Профессия')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='films.film', verbose_name='Фильм')),
                ('people', models.ManyToManyField(to='films.person', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник съемочной группы',
                'verbose_name_plural': 'Участники съемочной группы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.ManyToManyField(to='films.country', verbose_name='Страна'),
        ),
    ]
